Set up a "Hello world" project with two apps
Kaweesi-Matia/rails-react-frontend pull request #1
Opened 2023-03-03 15:38 UTC by Kaweesi-Matia

## Below is the description of the PR

- [ ] Create a new React app called 'hello-react-front-end'
- [ ] Initialize your project with Git.
- [ ] Create the App component with react-router.
- [ ] Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- [ ] Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- [ ] Display the random greeting in your Greeting component.

2023-03-03 17:22 UTC, jerryowusu requested changes
Hi @Kaweesi-Matia , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost there](https://user-images.githubusercontent.com/65233860/222786171-ff7c602a-10fc-4647-9993-a6879e562125.jpg)


## Highlights
Great effort so far :heavy_check_mark: 
No linter errors :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 17:22 UTC, jerryowusu commented on src/components/Greetings.js
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
The linters are suppose to help guide you to produce the best and standard code practices, kindly do not disable them.

2023-03-03 17:22 UTC, jerryowusu commented on src/components/Greetings.js
> +};
According to the project requirements, you are suppose to display the random greetings in your greeting component at the frontend. However, it shows null. Kindly check and fix it to make sure that the greetings are displayed as required.

2023-03-03 23:01 UTC, chrystalme requested changes
Hi @Kaweesi-Matia, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Linters works well ✅ 
- Adherence to gitflow ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 23:01 UTC, chrystalme commented on src/components/Greetings.js
> +  }, []);
Kindly include a dependency `dispatch` in the UseEffect hook. This will complete your useEffect and make it trigger to return the result.

2023-03-04 00:16 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @Kaweesi-Matia , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice app connection 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 18:11 UTC, merged